[project]
name = 'augurrank-smart-contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.amm-pool-v2-01]
path = 'contracts/amm-pool-v2-01.clar'
clarity_version = 3
epoch = 3.0

[contracts.augurrank-btc]
path = 'contracts/augurrank-btc.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
