[project]
name = 'augurrank-smart-contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.amm-pool-v2-01'

[[project.requirements]]
contract_id = 'SP102V8P0F7JX67ARQ77WEA3D3CFB5XW39REDT0AM.token-wstx-v2'

[[project.requirements]]
contract_id = 'SP2XD7417HGPRTREMKF748VNEQPDRR0RMANB7X1NK.token-susdt'

[[project.requirements]]
contract_id = 'SP2XD7417HGPRTREMKF748VNEQPDRR0RMANB7X1NK.token-abtc'
[contracts.amm-pool-v2-01]
path = 'contracts/amm-pool-v2-01.clar'
clarity_version = 3
epoch = 3.0

[contracts.augurrank-btc]
path = 'contracts/augurrank-btc.clar'
clarity_version = 3
epoch = 3.0

[contracts.playground]
path = 'contracts/playground.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
